trigger:
- release/*

pool:
  vmImage: 'windows-2022'

variables:
  solution: 'src\Blauhaus.DeviceServices.sln'
  buildPlatform: 'Any CPU'
  DotNetVersion: 7.0.100
  VersionName: $[replace(variables['Build.SourceBranchName'], 'refs/heads/release/', '')]
  OutputFolder: '$(build.artifactStagingDirectory)'

steps:  

- task: UseDotNet@2
  displayName: .NET Version
  inputs:
    packageType: 'sdk'
    version: '$(DotNetVersion)'
     
- task: VSBuild@1
  displayName: Build Client
  inputs:
    solution: './src/Blauhaus.DeviceServices.sln'
    configuration: 'Release_Xamarin'
    msbuildArgs: '/t:restore;build;pack /p:Version=$(VersionName) /p:PackageOutputPath=$(OutputFolder)'
    
- task: VSBuild@1
  displayName: Build MAUI
  inputs:
    solution: './src/Blauhaus.DeviceServices.sln'
    configuration: 'Release'
    msbuildArgs: '/t:restore;build;pack /p:Version=$(VersionName) /p:PackageOutputPath=$(OutputFolder)'
        
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(OutputFolder)/**/*.nupkg;!$(OutputFolder)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Blauhaus Nuget'

