name: Blauhaus .NET Standard and UWP Packages
on:
  push:
    branches:
    - release/*

jobs:

  build:
     runs-on: windows-latest
     steps:
     - uses: actions/checkout@v1
     - name: Set Version
       run: |
        npm install @actions/core --save
        node ./scripts/getversion.js
     - name: Build NuGet Packages
       run: | 
         dotnet pack -p:PackageVersion=${VERSION_NAME} .\src\Blauhaus.DeviceServices.sln --configuration Release_Windows --output .\
         dotnet test .\src\Blauhaus.DeviceServices.sln
     - name: Deploy NuGet Packages
       run: |
         dotnet nuget push \home\runner\work\Blauhaus.DeviceServices\Blauhaus.DeviceServices\Blauhaus.DeviceServices.${VERSION_NAME}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
         dotnet nuget push \home\runner\work\Blauhaus.DeviceServices\Blauhaus.DeviceServices\Blauhaus.DeviceServices.Abstractions.${VERSION_NAME}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
         dotnet nuget push \home\runner\work\Blauhaus.DeviceServices\Blauhaus.DeviceServices\Blauhaus.DeviceServices.Platforms.UWP.${VERSION_NAME}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
